build:
  script:
    - sudo docker build -t ireoo/api:latest -f ./docker/Dockerfile .
    - sudo docker tag ireoo/api:latest reg.qiyi.io/ireoo/api:latest
    - sudo docker push reg.qiyi.io/ireoo/api:latest