version: "3.2"

services:
  db:
    image: mongo:latest
    volumes:
      - /home/MongoDB:/data/db
    ports:
      - "27017:27017"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: meiyoumima

  api:
    depends_on:
      - db
    image: ireoo/api:latest
    ports:
      - 80
    deploy:
      mode: replicated
      replicas: 2
    environment:
      PORT: 80
      MONGODB: root:meiyoumima@db:27017
      MONGODB_OTHER: authSource=admin&authMechanism=SCRAM-SHA-1&ssl=false
      VIRTUAL_HOST: api.qiyi.io
      LETSENCRYPT_HOST: api.qiyi.io
      LETSENCRYPT_EMAIL: s@ireoo.com
