version: "3.2"

services:
  db:
    image: mongo:latest
    volumes:
      - /home/DATA/MongoDB:/data/db
    ports:
      - "27017:27017"
    networks:
      - proxy
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: meiyoumima

  api:
    depends_on:
      - db
    image: ireoo/api:latest
    ports:
      - 80
    networks:
      - proxy
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 2
    environment:
      PORT: 80
      MONGODB: root:meiyoumima@db:27017
      MONGODB_OTHER: authSource=admin&authMechanism=SCRAM-SHA-1&ssl=false
      VIRTUAL_HOST: test.qiyi.io
      LETSENCRYPT_HOST: test.qiyi.io
      LETSENCRYPT_EMAIL: s@ireoo.com

networks:
  proxy:
    external: true
