version: '3.3'

services:
	db:
		image: mongo:latest
		volumes:
			- /home/MongoDB:/data/db
		ports:
			- "27017:27017"
		restart: always
		environment:
			MONGO_INITDB_ROOT_USERNAME: root
			MONGO_INITDB_ROOT_PASSWORD: meiyoumima

	api:
		links:
			- db
		depends_on:
			- db
		image: ireoo/api:latest
		ports:
			- 80
		restart: always
		environment:
			PORT: 80
			MONGODB: root:meiyoumima@db:27017
			MONGODB_OTHER: authSource=admin&authMechanism=SCRAM-SHA-1&ssl=false
			VIRTUAL_HOST: api.ireoo.com
			LETSENCRYPT_HOST: api.ireoo.com
			LETSENCRYPT_EMAIL: s@ireoo.com

	nginxProxy:
		image: jwilder/nginx-proxy:latest
		ports:
			- "443:443"
			- "80:80"
		volumes:
			- /home/DATA/proxy/certs:/etc/nginx/certs
			- /home/DATA/proxy/dhparam:/etc/nginx/dhparam
			- /home/DATA/proxy/vhost.d:/etc/nginx/vhost.d
			- /var/run/docker.sock:/tmp/docker.sock
			- /home/DATA/proxy/html:/usr/share/nginx/html
		restart: always

	nginx-letsencrypt:
		image: jrcs/letsencrypt-nginx-proxy-companion:latest
		volumes:
		  - /var/run/docker.sock:/tmp/docker.sock
		  - /home/DATA/proxy/html:/usr/share/nginx/html
		  - /var/run/docker.sock:/var/run/docker.sock
		  - /home/DATA/proxy/certs:/etc/nginx/certs
		  - /home/DATA/proxy/dhparam:/etc/nginx/dhparam
		  - /home/DATA/proxy/vhost.d:/etc/nginx/vhost.d
