version: '3.3'

services:
   db:
     image: mongo:latest
     volumes:
       - /home/MongoDB:/data/db
     restart: always
     environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: meiyoumima

   api:
     depends_on:
       - db
     image: ireoo/api:latest
     ports:
       - "80:80"
     restart: always
     environment:
       PORT: 80
