version: "2.2"

services:
    db:
        image: mongo:latest
        volumes:
            - /home/MongoDB:/data/db
        ports:
            - "27017:27017"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: meiyoumima
