version: "3.2"

services:
  nginxProxy:
    image: dmp1ce/nginx-proxy-letsencrypt:latest
    ports:
      - "443:443"
      - "80:80"
    networks:
      - ingress
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - /home/DATA/proxy/certs:/etc/nginx/certs
      - /home/DATA/proxy/dhparam:/etc/nginx/dhparam
      - /home/DATA/proxy/vhost.d:/etc/nginx/vhost.d
      - /home/DATA/proxy/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock
      - /home/DATA/proxy/html:/usr/share/nginx/html

networks:
  proxy:
    external: true
