version: "3.2"

services:
  nginxProxy:
    image: dmp1ce/nginx-proxy-letsencrypt:latest
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - nginx_data1:/etc/nginx
      - /var/run/docker.sock:/tmp/docker.sock
      - nginx_html1:/usr/share/nginx/html

volumes:
  nginx_data1:
  nginx_html1:

networks:
  proxy:
    external: true
