version: "2.2"

services:
  nginxProxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "443:443"
      - "80:80"
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - nginx_data:/etc/nginx
      - /var/run/docker.sock:/tmp/docker.sock
      - nginx_html:/usr/share/nginx/html
    restart: always

  nginxLetsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes_from:
      - nginxProxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  nginx_data:
  nginx_html: