version: "3.2"

services:
  nginxProxy:
    image: dmp1ce/nginx-proxy-letsencrypt:latest
    ports:
      - "443:443"
      - "80:80"
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - nginx_data:/etc/nginx
      - /var/run/docker.sock:/tmp/docker.sock
      - nginx_html:/usr/share/nginx/html

volumes:
  nginx_data:
  nginx_html:

networks:
  nginx_default:
    driver: overlay
    attachable: true
