version: "3.2"

services:
  nginxProxy:
    image: dmp1ce/nginx-proxy-letsencrypt:latest
    ports:
      - "443:443"
      - "80:80"
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - /home/DATA/proxy/nginx:/etc/nginx
      - /var/run/docker.sock:/tmp/docker.sock
      - /home/DATA/proxy/html:/usr/share/nginx/html

volumes:
  nginx_data1:
  nginx_html1:

networks:
  proxy:
    external: true
