name: CI

on:
  push:
    branches:
      - master

jobs:
  macos:
    runs-on: macOS-latest
    strategy:
      matrix:
        node: [12, 13]
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      - name: install
        uses: actions/checkout@master
        with:
          node-version: "latest"

      - name: build
        run: |
          npm i
          npm run build

      - name: upload
        uses: actions/upload-artifact@master
        with:
          name: API-${{matrix.node}}-${{matrix.os}}
          path: ./build/

      - name: release
        uses: softprops/action-gh-release@v0.1.0
        with:
          name: test-${{matrix.node}}-${{matrix.os}}
          files: ./build/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
