name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  macos:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node: [12, 13]
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - name: install
        uses: actions/checkout@master
        with:
          node-version: "latest"

      - name: build
        run: |
          npm i
          npm run build

      - name: release
        uses: softprops/action-gh-release@v0.1.0
        with:
          files: |
          ./build/api.exe
          ./build/api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
