name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  macos:
    runs-on: macOS-latest

    # strategy:
    #   matrix:
    #     node: [12, 13]
    #     os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - name: install
        uses: actions/checkout@master
        with:
          node-version: "latest"

      - name: build
        run: |
          npm i
          npm run build

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
